kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
